

settings = {
    "DB": {
        "user": "root",
        "password": "",
        "host": "localhost",
        "database": "twitter_news"
    },

    "news_accounts": ['BBCnews',
                      'CNN',
                      'abc',
                      'abcnews',
                      'abcnewslive',
                      'abcworldnews',
                      'actualidadrt',
                      'afp',
                      'ajenglish',
                      'ap',
                      'ap_noticias',
                      'bbcbreaking',
                      'bbcengland',
                      'bbcmundo',
                      'bbcmundo_ultimo',
                      'bbcnews',
                      'bbcnewsasia',
                      'bbcworld',
                      'bloombergnews',
                      'bostonglobe',
                      'breaking911',
                      'breakingnews',
                      'breakingnewsuk',
                      'breakingpol',
                      'business',
                      'cbsnews',
                      'channel4news',
                      'cnnbrk',
                      'cnnee',
                      'cnni',
                      'cnnlive',
                      'cp24',
                      'efenoticias',
                      'el_pais',
                      'elmundoes',
                      'forbes',
                      'foxheadlines',
                      'foxnews',
                      'foxnewsalert',
                      'ft',
                      'googlenews',
                      'googlenewsstand',
                      'guardian',
                      'guardiannews',
                      'huffpost',
                      'independent',
                      'japantoday',
                      'jerusalem_post',
                      'jtanews',
                      'latimes',
                      'msnbc',
                      'msnbc_breaking',
                      'nbcnews',
                      'nbcnightlynews',
                      'ndtv',
                      'newshour',
                      'newsweek',
                      'noticiamerica',
                      'npr',
                      'nydailynews',
                      'nypost',
                      'nytimes',
                      'nytimesphoto',
                      'reuters',
                      'reuterslive',
                      'rt_com',
                      'salon',
                      'skynews',
                      'skynewsbreak',
                      'slate',
                      'telegraphnews',
                      'theeconomist',
                      'thetimes',
                      'time',
                      'twcbreaking',
                      'uninoticias',
                      'usatoday',
                      'usnews',
                      'vox',
                      'washingtonpost',
                      'wsj',
                      'wsjbreakingnews',
                      'yahoonews',
                      'yahoonoticias']
}